server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: mesmos2001
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

customer-service:
  url: http://customer-service/customers