server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb:http://customer-service
          predicates:
            - Path=/customers/**
        - id: account-service
          uri: lb:http://account-service
          predicates:
            - Path=/accounts/**